---
output:
  bookdown::gitbook:
  pdf_document: default
  html_document: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
library(tidyr) 
library(dplyr)
library(qwraps2)
library(gplots)
options(digits=2)
```

# Random and Mixed Effect Models {#ch:nested}

> If your experiment needs statistics, you ought to have done a better
experiment.
> ---  Ernest Rutherford

## Nested design

* Motivations for a nested design
* Nested design with fixed factors 
    - Sampling scheme
    - Hypothesis testing
    - Causal interpretation
* Nested design with random factors
* Nested design with mixed factors
    - Repeated measures design 



## Random effects model

* One-way ANOVA model with random effects
* Estimation
    - Decomposition of variances
* Hypothesis testing and confidence intervals 
* Mixed effects model 
* Unbalanced mixed and random effect models
    - REML (see among others, [this note](http://www2.compute.dtu.dk/courses/02429/enotepdfs/eNote-10.pdf))
    
For more discussion, see Chapter 7 [here](https://stat.ethz.ch/~meier/teaching/anova/random-and-mixed-effects-models.html).

## Learning Objectives

* Students are able to write down the two-way ANOVA model with random effects.
* Students can properly decide whether to model a factor using fixed or random effects. 
* Students recognize the key assumptions associated with the random effects model. 
* Students can implement the aforemened tasks in `R`.
* Students can explore extension of random effect model on the Internet. 

